language: java

jdk:
  - openjdk8

script: mvn clean package

notifications:
  email:
    recipients:
      - surya_uppuluri@outlook.com
      - usuryasatyakumar@gmail.com
    on_failure: always
    on_success: always

after_success:
  - bash <(curl -s https://codecov.io/bash)